baseURL = "https://k4i.top"
title = "k4i's blog"
theme = "zzo-sky"
enableRobotsTXT = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

summaryLength = 70
buildFuture = true

copyright = 'All content is subject to the license of <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a> .'
timeout = 10000
enableEmoji = true
paginate = 10
rssLimit = 100

enableGitInfo = true
googleAnalytics = "UA-163569254-1"

[Author]
  name = '<a href="https://k4i.top" class="theme-link">k4i</a>'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[mediaTypes]
 [mediaTypes."text/plain"]
   suffixes = ["md"]

[outputs]
  page = ["HTML", "MarkDown"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true
  [outputFormats.MarkDown]
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"