[en]
  title = "Kyle's Blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
  title = "sky的博客"
  languageName = "简体中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"

# [ko]
#   # title = "Hugo Zzo Theme"
#   languageName = "한국어"
#   weight = 2
#   languagedir = "ltr"
#   contentdir = "content/ko"
